In [2]:
import pandas as pd
import numpy as np
import re
import math
import sklearn as sk
import sklearn
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, chi2

data = pd.read_csv('prep_data.csv')

data_Y=data['completed_ratio']
data_X=data.loc[:, data.columns != 'completed_ratio']

X_train, X_test, y_train, y_test = train_test_split(data_X , data_Y, test_size=0.35, random_state=0)
selector = SelectKBest(chi2, k=20)
selector.fit(X_train, y_train)
X_train = selector.transform(X_train)
X_test = selector.transform(X_test)
X_train=pd.DataFrame(X_train)
pd.set_option('max_columns', None)
display(X_train.iloc[[0]])
pd.reset_option('max_columns')

0         1         2    3    4    5    6    7    8    9    10   11  \
0  166.0  0.037762  0.087205  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0   

    12   13   14   15   16   17   18   19  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [4]:
knc = SVC(kernel='linear',C=100)
knc.fit(X_train, y_train)
pred=knc.predict(X_test)
print("Confusion matrix on test set:\n",sklearn.metrics.confusion_matrix(y_test, pred))
print("\nAccuracy on test set: ",sklearn.metrics.accuracy_score(y_test, pred))
print("\nNumber of supports: ",np.sum(knc.n_support_), "(",np.sum(np.abs(knc.dual_coef_)==100) ,"of them have slacks)")
print("Prop. of supports: ",np.sum(knc.n_support_)/X_train.shape[0])

Confusion matrix on test set:
 [[171   0  44   0]
 [  7   0  11   0]
 [ 58   0  49   4]
 [  1   0   0   5]]

Accuracy on test set:  0.6428571428571429

Number of supports:  323 ( 385 of them have slacks)
Prop. of supports:  0.4969230769230769
